# Header

menu:
  文章·article: /archives
  生活·douban: /douban
  玩物·demo: /demo

# SubNav
subnav:
  weibo: "http://weibo.com/hust2012jiangkai"
  rss: "/atom.xml"
  zhihu: "http://www.zhihu.com/people/jiangkai-paranoid"
  mail: "mailto:hust2012jiangkai@gamil.com"
  instagram: "https://www.instagram.com/paranoid_jk/"
  twitter: "https://twitter.com/jiang_paranoid"
  linkedin: "https://www.linkedin.com/in/jiangkaicv"


# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
# root:

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
google_analytics: ''
favicon: "/img/favicon.png"

#你的头像url
avatar: "https://avatars3.githubusercontent.com/u/7971415?v=3&s=460"

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: paranoidjk

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  friends: '友链'
  aboutme: '关于我'

#是否开启云标签
tagcloud: true

#是否开启友情链接
friends:
  和我交换: "mailto:hust2012jiangkai@gamil.com"

#是否开启“关于我”。
aboutme: "「何须更问浮生事 只此浮生是梦中」"




